# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TkgiKubectx < Formula
  desc "Faster way to switch between clusters and namespaces in kubectl with support of tkgi login before switch"
  homepage "https://github.com/jakuboskera/tkgi-kubectx"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.1.0/tkgi-kubectx_v0.1.0_darwin_arm64.tar.gz"
      sha256 "2caa36f29433814a4dfa74d66962a21d585bc09715f068bcf67d6084aaa2a783"

      def install
        bin.install "tkgi-kubectx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.1.0/tkgi-kubectx_v0.1.0_darwin_x86_64.tar.gz"
      sha256 "052f80f7314a7e22f781bbd2159768d39dc01e067f8673695a3a2ca23db6d3e0"

      def install
        bin.install "tkgi-kubectx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.1.0/tkgi-kubectx_v0.1.0_linux_x86_64.tar.gz"
      sha256 "a703c0784566020bb594169c7eab557f26b99cdaa8f86d03c26ca867b2c3ee86"

      def install
        bin.install "tkgi-kubectx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.1.0/tkgi-kubectx_v0.1.0_linux_arm64.tar.gz"
      sha256 "fd81e0166eade28010a048de4bf6fd26273cfe707fcc218a17908a58fbd39b6c"

      def install
        bin.install "tkgi-kubectx"
      end
    end
  end

  test do
    system "#{bin}/tkgi-kubectx --version"
  end
end
