# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TkgiKubectx < Formula
  desc "Faster way to switch between clusters and namespaces in kubectl with support of tkgi login before switch"
  homepage "https://github.com/jakuboskera/tkgi-kubectx"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.2.0/tkgi-kubectx_v0.2.0_darwin_x86_64.tar.gz"
      sha256 "71e0a263b0c955ab4e64e1735cfcb26c086204e710904f46745eeecdefaed32d"

      def install
        bin.install "tkgi-kubectx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.2.0/tkgi-kubectx_v0.2.0_darwin_arm64.tar.gz"
      sha256 "26f5a2e4c279fb0601f238b2b16a175a59fcd34c02466beab49458df99f523ce"

      def install
        bin.install "tkgi-kubectx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.2.0/tkgi-kubectx_v0.2.0_linux_arm64.tar.gz"
      sha256 "5be120a0aaa91970599e36e5da9b2fba5f123b6f4c83105159a66800b6f8c2f4"

      def install
        bin.install "tkgi-kubectx"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.2.0/tkgi-kubectx_v0.2.0_linux_armhf.tar.gz"
      sha256 "eac1139a59dc6f1db9b43c4e2e866d08a3e14250e1f03c400245524686c8e055"

      def install
        bin.install "tkgi-kubectx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jakuboskera/tkgi-kubectx/releases/download/v0.2.0/tkgi-kubectx_v0.2.0_linux_x86_64.tar.gz"
      sha256 "68901776177e81f45b58397f2147d2d8f11ed8ce950096c5866d76652db1bf4a"

      def install
        bin.install "tkgi-kubectx"
      end
    end
  end

  test do
    system "#{bin}/tkgi-kubectx --version"
  end
end
